/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;

import java.util.ArrayList;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import modeloqytetet.Calle;
import modeloqytetet.Casilla;
import modeloqytetet.MetodoSalirCarcel;
import modeloqytetet.Qytetet;
import modeloqytetet.TipoCasilla;
import modeloqytetet.TituloPropiedad;

public class ControladorQytetet extends javax.swing.JFrame {

        private Qytetet modeloQytetet  ;
        private Calle calle;// = (Calle)this.modeloQytetet.getJugadorActual().getCasillaActual();//new Calle(5000,0,0,0,TipoCasilla.CALLE,new TituloPropiedad("aux",false,50,10,150,250));
        private boolean vender = false ;
        private boolean hipotecar = false;
        private boolean edificarCasa = false;
        private boolean edificarHotel = false;

    public Qytetet getModeloQytetet() {
        return modeloQytetet;
    }

    public void setModeloQytetet(ArrayList<String> nombres) {
        this.modeloQytetet = Qytetet.getInstance(nombres);
    } 
    /**
     * Creates new form ControladorQytetet
     */
    public ControladorQytetet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton_siguiente_jugador = new javax.swing.JButton();
        Boton_aplicar_sorpresa = new javax.swing.JButton();
        Boton_comprar_propiedad = new javax.swing.JButton();
        Boton_jugar = new javax.swing.JButton();
        Boton_salir_calcel_pagando = new javax.swing.JButton();
        Boton_salir_carcel_dado = new javax.swing.JButton();
        vistaQytetet = new GUIQytetet.VistaQytetet();
        Boton_vender_propiedad = new javax.swing.JButton();
        Boton_Edificar_casa = new javax.swing.JButton();
        Boton_edificar_hotel = new javax.swing.JButton();
        Boton_hipotecar_propiedad = new javax.swing.JButton();
        GestionInmoviliaria = new javax.swing.JButton();
        Boton_Cancelar_Hipoteca = new javax.swing.JButton();
        EdificarCasaAqui = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Boton_siguiente_jugador.setText("Siguiente Jugador");
        Boton_siguiente_jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_siguiente_jugadorActionPerformed(evt);
            }
        });

        Boton_aplicar_sorpresa.setText("Aplicar Sorpresa");
        Boton_aplicar_sorpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_aplicar_sorpresaActionPerformed(evt);
            }
        });

        Boton_comprar_propiedad.setText("Comprar Propiedad");
        Boton_comprar_propiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_comprar_propiedadActionPerformed(evt);
            }
        });

        Boton_jugar.setText("Jugar");
        Boton_jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_jugarActionPerformed(evt);
            }
        });

        Boton_salir_calcel_pagando.setText("Salir Cárcel Pagando");
        Boton_salir_calcel_pagando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_salir_calcel_pagandoActionPerformed(evt);
            }
        });

        Boton_salir_carcel_dado.setText("Salir Cárcel Dado");
        Boton_salir_carcel_dado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_salir_carcel_dadoActionPerformed(evt);
            }
        });

        Boton_vender_propiedad.setText("Vender Propiedad");
        Boton_vender_propiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_vender_propiedadActionPerformed(evt);
            }
        });

        Boton_Edificar_casa.setText("Edificar Casa");
        Boton_Edificar_casa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Edificar_casaActionPerformed(evt);
            }
        });

        Boton_edificar_hotel.setText("Edificar Hotel");
        Boton_edificar_hotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_edificar_hotelActionPerformed(evt);
            }
        });

        Boton_hipotecar_propiedad.setText("Hipotecar Propiedad");
        Boton_hipotecar_propiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_hipotecar_propiedadActionPerformed(evt);
            }
        });

        GestionInmoviliaria.setText("Gestion Inmoviliaria");
        GestionInmoviliaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionInmoviliariaActionPerformed(evt);
            }
        });

        Boton_Cancelar_Hipoteca.setText("Cancelar Hipoteca");
        Boton_Cancelar_Hipoteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Cancelar_HipotecaActionPerformed(evt);
            }
        });

        EdificarCasaAqui.setText("Edificar Casa Aqui");
        EdificarCasaAqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdificarCasaAquiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(vistaQytetet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 190, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Boton_vender_propiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Boton_Edificar_casa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Boton_edificar_hotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Boton_hipotecar_propiedad, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GestionInmoviliaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Boton_Cancelar_Hipoteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Boton_comprar_propiedad, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(Boton_aplicar_sorpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Boton_salir_calcel_pagando, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(Boton_salir_carcel_dado, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(EdificarCasaAqui)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Boton_jugar, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(Boton_siguiente_jugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vistaQytetet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Boton_jugar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(Boton_siguiente_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(Boton_comprar_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Boton_salir_carcel_dado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Boton_salir_calcel_pagando, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(Boton_aplicar_sorpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GestionInmoviliaria, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Boton_Edificar_casa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Boton_edificar_hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Boton_vender_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Boton_Cancelar_Hipoteca, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Boton_hipotecar_propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EdificarCasaAqui)
                        .addGap(41, 41, 41)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_siguiente_jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_siguiente_jugadorActionPerformed
        // TODO add your handling code here:
        modeloQytetet.siguienteJugador();
        Boton_siguiente_jugador.setEnabled(false);
        Boton_jugar.setEnabled(true);
        //propiedades(false);
        actualizar(modeloQytetet);
    }//GEN-LAST:event_Boton_siguiente_jugadorActionPerformed

    private void Boton_aplicar_sorpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_aplicar_sorpresaActionPerformed
        // TODO add your handling code here: cuando tengo una sorpresa es obligatoria ? desabilitar el boton de siguiente jugador. ******************************************
        boolean aplicada = modeloQytetet.aplicarSorpresa();
        if (aplicada){
            JOptionPane.showMessageDialog(this, "He plicado la sorpresa "); 
        }
        Boton_aplicar_sorpresa.setEnabled(false);
        actualizar(modeloQytetet);
    }//GEN-LAST:event_Boton_aplicar_sorpresaActionPerformed

    private void Boton_comprar_propiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_comprar_propiedadActionPerformed
        // TODO add your handling code here:
        boolean comprado = modeloQytetet.comprarTituloPropiedad();
        if (comprado){
            JOptionPane.showMessageDialog(this, "He comprado el titulo de propiedad ");  
        }
        //propiedades(true); ESTE ES EL METODO QUE TENIAMOS MAL, SI LO HACEMOS NOS COMPRA LA PROPIEDAD Y DIRECTAMENTE LA HIPOTECA
        this.Boton_comprar_propiedad.setEnabled(false);
        //EXAMEN INI
        this.EdificarCasaAqui.setEnabled(true);
        //EXAMEN FIN
        this.GestionInmoviliaria.setEnabled(true);
        actualizar(modeloQytetet);
    }//GEN-LAST:event_Boton_comprar_propiedadActionPerformed

    private void Boton_jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_jugarActionPerformed
        // TODO add your handling code here:
        boolean tienepropietario = modeloQytetet.jugar();
        
        if(tienepropietario){
           JOptionPane.showMessageDialog(this, "La casilla tiene propietario y hemos pagado el coste si la casilla no es mia");   
        }
        
        if(modeloQytetet.getJugadorActual().getEncarcelado()){
            this.Boton_salir_calcel_pagando.setEnabled(true);
            this.Boton_salir_carcel_dado.setEnabled(true);
        }//El jugador no está encarcelado y puede continuar jugando
        
        else if(modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == TipoCasilla.SORPRESA){
            this.Boton_aplicar_sorpresa.setEnabled(true);
        }else if(modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == TipoCasilla.CALLE){
            calle = (Calle)modeloQytetet.getJugadorActual().getCasillaActual();
            if(!calle.tengoPropietario() && calle.getTituloPropiedad().getNombre() != modeloQytetet.getJugadorActual().getNombre()){
                Boton_comprar_propiedad.setEnabled(true);
            }
        }
        if(this.modeloQytetet.getJugadorActual().tengoPropiedades()){   //Abro la gestión de propiedades después de jugar, es decir, de moverme falta meterselo cuando compre la primera.
            this.GestionInmoviliaria.setEnabled(true);
        }
        
        this.Boton_jugar.setEnabled(false);
        this.Boton_siguiente_jugador.setEnabled(true);
        //****************************************************************************
        if(modeloQytetet.getJugadorActual().getSaldo() <= 0){//if(jugador.getSaldo() <= 0){
                JOptionPane.showMessageDialog(this,"jugador en bancarrota, se termina el juego \n");
                JOptionPane.showMessageDialog(this," ranking de mejor a peor \n");
                Map map =  modeloQytetet.obtenerRanking();
                map.forEach((k,v) -> JOptionPane.showMessageDialog(this,"Key: " + k + ": Value: " + v));
                finalizar();
        }
        //****************************************************************************
        actualizar(modeloQytetet);
        //this.vistaQytetet.actualizar(modeloQytetet);
    }//GEN-LAST:event_Boton_jugarActionPerformed
        //*************************************************************************************
    
    private void Boton_salir_calcel_pagandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_salir_calcel_pagandoActionPerformed
        // TODO add your handling code here:
        boolean resultado = modeloQytetet.intentarSalirCarcel(MetodoSalirCarcel.PAGANDOLIBERTAD);
        this.Boton_salir_calcel_pagando.setEnabled(false);
        this.Boton_salir_carcel_dado.setEnabled(false);
        if(resultado){
            JOptionPane.showMessageDialog(this, "Sales de la cárcel");
            this.Boton_jugar.setEnabled(true);
        }else {
            JOptionPane.showMessageDialog(this, "NO sales de la carcel");
            this.Boton_siguiente_jugador.setEnabled(true);
        }
        actualizar(modeloQytetet);
       
    }//GEN-LAST:event_Boton_salir_calcel_pagandoActionPerformed

    private void Boton_salir_carcel_dadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_salir_carcel_dadoActionPerformed
        // TODO add your handling code here:
        boolean resultado = modeloQytetet.intentarSalirCarcel(MetodoSalirCarcel.TIRANDODADO);
        this.Boton_salir_calcel_pagando.setEnabled(false);
        this.Boton_salir_carcel_dado.setEnabled(false);
        if(resultado){
            JOptionPane.showMessageDialog(this, "Sales de la cárcel");
            this.Boton_jugar.setEnabled(true);
        }else {
            JOptionPane.showMessageDialog(this, "NO sales de la carcel");
            this.Boton_siguiente_jugador.setEnabled(true);
        }
        actualizar(modeloQytetet);
        //this.vistaQytetet.actualizar(modeloQytetet);
    }//GEN-LAST:event_Boton_salir_carcel_dadoActionPerformed

//**************************************** BOTONES NO OBLIGATORIOS *****************************************
   
    private Calle ElegirPropiedad(ArrayList<Calle> calles){
        String[] nombres = new String[calles.size()];
        for (int i = 0; i < calles.size(); i++) {
            nombres[i] = calles.get(i).getTituloPropiedad().getNombre();
        }
        int calle = JOptionPane.showOptionDialog(null, "Elige la propiedad de entre las que tienes: ", "Eleccion Propiedades", JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, nombres, nombres[0]);

        return calles.get(calle); //Devuelve la calle correspondiente a la indicada arriba
        
    } 
    
    
    
    
    private ArrayList<Calle> ObtenerCalles(){
        ArrayList<Calle> calles = new ArrayList();
        Calle calle; 
        
        for(int i = 0; i < modeloQytetet.getJugadorActual().getPropiedades().size(); i++){
            calle = modeloQytetet.getJugadorActual().getPropiedades().get(i).getCasilla();
            calles.add(calle);
        }
        return calles;
    }
    
    
    private void Boton_vender_propiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_vender_propiedadActionPerformed
        // TODO add your handling code here:
        ArrayList<Calle> calles;
        boolean vendido = false;
        
        
        calles = ObtenerCalles();//Ya que las propiedades que se pueden vender son las que no están hipotecadas.
        JOptionPane.showMessageDialog(this, " Elegir Propiedad ");
        //Para ver si pila bien las calles
        //for(int i=0; i < calles.size();i++)
        //    JOptionPane.showMessageDialog(this, calles.get(i).toString());
        Calle calle_a_vender = ElegirPropiedad(calles);
        
        //Para ver si me pila bien la calle que quiero vender:
        //JOptionPane.showMessageDialog(this, calle_a_vender.toString());
        
        vendido = modeloQytetet.venderPropiedad(calle_a_vender);
        if(vendido){
                JOptionPane.showMessageDialog(this, " He vendido mi propiedad correctamente ");
        }
        else if (!vendido){
            JOptionPane.showMessageDialog(this, " No he conseguido vender mi propiedad correctamente ");
        }
        actualizar(modeloQytetet);
        if(modeloQytetet.getJugadorActual().getPropiedades().size() < 1) //Si me quedo sin propiedades, desactivo toda la gestión inmobiliaria.
            this.Boton_vender_propiedad.setEnabled(false);
            this.Boton_Cancelar_Hipoteca.setEnabled(false);
            this.Boton_Edificar_casa.setEnabled(false);
            this.Boton_edificar_hotel.setEnabled(false);
            this.Boton_hipotecar_propiedad.setEnabled(false);
            this.GestionInmoviliaria.setEnabled(false);
    }//GEN-LAST:event_Boton_vender_propiedadActionPerformed

    private void Boton_hipotecar_propiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_hipotecar_propiedadActionPerformed
        // TODO add your handling code here:
        ArrayList<Calle> calles;
        boolean hipotecada = false;
        calles = ObtenerCalles();      //Ya que las calles que se pueden hipotecar son las que no están hipotecadas ya
        
        JOptionPane.showMessageDialog(this, " Elegir Propiedad ");
        //Para ver si pila bien las calles
        //for(int i=0; i < calles.size();i++)
            //JOptionPane.showMessageDialog(this, calles.get(i).toString());
        
        
        Calle calle_a_hipotecar = ElegirPropiedad(calles);
        hipotecada = modeloQytetet.hipotecarPropiedad(calle_a_hipotecar);
        if(hipotecada){
            JOptionPane.showMessageDialog(this, " He hipotecado mi propiedad correctamente ");
        }
        else if (!hipotecada){
            JOptionPane.showMessageDialog(this, " No he conseguido hipotecar mi propiedad correctamente ");
        }
        actualizar(modeloQytetet);
    }//GEN-LAST:event_Boton_hipotecar_propiedadActionPerformed

    private void Boton_Edificar_casaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Edificar_casaActionPerformed
        // TODO add your handling code here:
        
        ArrayList<Calle> calles = new ArrayList();
        boolean edificada = false;
        calles = ObtenerCalles();
        JOptionPane.showMessageDialog(this, " Elegir Propiedad ");
        
        //for(int i=0; i < calles.size();i++)
            //JOptionPane.showMessageDialog(this, calles.get(i).toString());
        Calle calle_a_edificar = ElegirPropiedad(calles);
        edificada = this.modeloQytetet.edificarCasa(calle_a_edificar);
        if(edificada){
            JOptionPane.showMessageDialog(this, " He edificado una casa correctamente ");
        }
        else if (!edificada){
            JOptionPane.showMessageDialog(this, " No he conseguido edificar una casa");
        }
        actualizar(modeloQytetet);
        //this.vistaQytetet.actualizar(modeloQytetet);
    }//GEN-LAST:event_Boton_Edificar_casaActionPerformed

    private void Boton_edificar_hotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_edificar_hotelActionPerformed
        // TODO add your handling code here:
        ArrayList<Calle> calles = new ArrayList();
        boolean edificada = false;
        calles = ObtenerCalles();
        JOptionPane.showMessageDialog(this, " Elegir Propiedad ");
        
        for(int i=0; i < calles.size();i++)
            JOptionPane.showMessageDialog(this, calles.get(i).toString());
        Calle calle_a_edificar = ElegirPropiedad(calles);
        edificada = this.modeloQytetet.edificarHotel(calle_a_edificar);
        if(edificada){
            JOptionPane.showMessageDialog(this, " He edificado un hotel correctamente ");
        }
        else if (!edificada){
            JOptionPane.showMessageDialog(this, " No he conseguido edificar un hotel ");
        }
        actualizar(modeloQytetet);
    }//GEN-LAST:event_Boton_edificar_hotelActionPerformed

    private void Boton_Cancelar_HipotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Cancelar_HipotecaActionPerformed
        // TODO add your handling code here:
        ArrayList<Calle> calles;
        boolean cancelada = false;
        
        
        calles = ObtenerCalles();//Ya que las propiedades que se pueden vender son las que no están hipotecadas.
        JOptionPane.showMessageDialog(this, " Elegir Propiedad ");
        //Para ver si pila bien las calles
        //for(int i=0; i < calles.size();i++)
        //    JOptionPane.showMessageDialog(this, calles.get(i).toString());
        Calle calle_a_cancelar = ElegirPropiedad(calles);
        
        //Para ver si me pila bien la calle que quiero vender:
        //JOptionPane.showMessageDialog(this, calle_a_vender.toString());
        
        cancelada = modeloQytetet.cancelarHipoteca(calle_a_cancelar);
        if(cancelada){
                JOptionPane.showMessageDialog(this, " He cancelado la hipoteca correctamente ");
        }
        else if (!cancelada){
            JOptionPane.showMessageDialog(this, " No he conseguido cancelar la hipoteca correctamente, mire a ver si realmente estaba hipotecada o tiene dinero. ");
        }
        actualizar(modeloQytetet);
    }//GEN-LAST:event_Boton_Cancelar_HipotecaActionPerformed

    private void GestionInmoviliariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionInmoviliariaActionPerformed
        // TODO add your handling code here:
        if (this.modeloQytetet.getJugadorActual().tengoPropiedades()) {
            this.Boton_Edificar_casa.setEnabled(true);
            this.Boton_edificar_hotel.setEnabled(true);
            this.Boton_Cancelar_Hipoteca.setEnabled(true);
            this.Boton_vender_propiedad.setEnabled(true);
            //this.mostrarPropiedades.setEnabled(true);
            this.Boton_hipotecar_propiedad.setEnabled(true);
            //EXAMEN INI
            this.EdificarCasaAqui.setEnabled(true);
            //EXAMEN FIN
        }

        //activamos para salir.
        //this.salirGestionInmobiliaria.setEnabled(true);

        actualizar(modeloQytetet);
    }//GEN-LAST:event_GestionInmoviliariaActionPerformed

    //EXAMEN INI
    private void EdificarCasaAquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdificarCasaAquiActionPerformed
        // TODO add your handling code here:
        Calle calle_a_edificar = (Calle)this.modeloQytetet.getJugadorActual().getCasillaActual();
        boolean edificada = this.modeloQytetet.edificarCasa(calle_a_edificar);
        if(edificada){
            JOptionPane.showMessageDialog(this, " He edificado una casa correctamente ");
        }
        else if (!edificada){
            JOptionPane.showMessageDialog(this, " No he conseguido edificar una casa");
        }
        actualizar(modeloQytetet);
    }//GEN-LAST:event_EdificarCasaAquiActionPerformed
    //EXAMEN FIN
    
//**************************************************************************************************************
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args){
        
        ControladorQytetet controladorQytetet= new ControladorQytetet();
        Dado.createInstance(controladorQytetet);
        CapturaNombreJugadores capturaNombres = new CapturaNombreJugadores(controladorQytetet, true);
        ArrayList<String> nombres= capturaNombres.obtenerNombres();
        controladorQytetet.setModeloQytetet(nombres);
        controladorQytetet.actualizar(controladorQytetet.modeloQytetet);
        //controladorQytetet.vistaQytetet.actualizar(controladorQytetet.getModeloQytetet());
        /*controladorQytetet.Boton_comprar_propiedad.setEnabled(false);
        controladorQytetet.Boton_siguiente_jugador.setEnabled(false);
        controladorQytetet.Boton_aplicar_sorpresa.setEnabled(false);
        controladorQytetet.Boton_salir_calcel_pagando.setEnabled(false);
        controladorQytetet.Boton_salir_carcel_dado.setEnabled(false);*/
        controladorQytetet.habilitarComenzarTurno();
        controladorQytetet.setVisible(true); //Esta debe ser la última línea de código del main
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Cancelar_Hipoteca;
    private javax.swing.JButton Boton_Edificar_casa;
    private javax.swing.JButton Boton_aplicar_sorpresa;
    private javax.swing.JButton Boton_comprar_propiedad;
    private javax.swing.JButton Boton_edificar_hotel;
    private javax.swing.JButton Boton_hipotecar_propiedad;
    private javax.swing.JButton Boton_jugar;
    private javax.swing.JButton Boton_salir_calcel_pagando;
    private javax.swing.JButton Boton_salir_carcel_dado;
    private javax.swing.JButton Boton_siguiente_jugador;
    private javax.swing.JButton Boton_vender_propiedad;
    private javax.swing.JButton EdificarCasaAqui;
    private javax.swing.JButton GestionInmoviliaria;
    private GUIQytetet.VistaQytetet vistaQytetet;
    // End of variables declaration//GEN-END:variables

    public void habilitarComenzarTurno(){
        this.GestionInmoviliaria.setEnabled(false);
        this.Boton_comprar_propiedad.setEnabled(false);
        this.Boton_siguiente_jugador.setEnabled(false);
        this.Boton_aplicar_sorpresa.setEnabled(false);
        this.Boton_salir_calcel_pagando.setEnabled(false);
        this.Boton_salir_carcel_dado.setEnabled(false);
        //propiedades(false);
        this.Boton_Edificar_casa.setEnabled(false);
        this.Boton_edificar_hotel.setEnabled(false);
        this.Boton_vender_propiedad.setEnabled(false);
        this.Boton_hipotecar_propiedad.setEnabled(false);
        this.Boton_Cancelar_Hipoteca.setEnabled(false);
        //EXAMEN INI
        this.EdificarCasaAqui.setEnabled(false);
        //EXAMEN FIN
        
        if(modeloQytetet.getJugadorActual().getEncarcelado()){
            this.Boton_salir_calcel_pagando.setEnabled(true);
            this.Boton_salir_carcel_dado.setEnabled(true);
        }
        else
            this.Boton_jugar.setEnabled(true);
    }
    
    private void finalizar(){
            this.Boton_comprar_propiedad.setEnabled(false);
            this.Boton_siguiente_jugador.setEnabled(false);
            this.Boton_aplicar_sorpresa.setEnabled(false);
            this.Boton_salir_calcel_pagando.setEnabled(false);
            this.Boton_salir_carcel_dado.setEnabled(false);
            this.Boton_jugar.setEnabled(false);
            this.Boton_Edificar_casa.setEnabled(false);
            this.Boton_edificar_hotel.setEnabled(false);
            this.Boton_vender_propiedad.setEnabled(false);
            this.Boton_hipotecar_propiedad.setEnabled(false);
            this.Boton_Cancelar_Hipoteca.setEnabled(false);
            //propiedades(false);
    }
    /*
    public void propiedades(boolean aux){
        if(calle != null){
            if(this.modeloQytetet.edificarCasa(calle) || aux == false){
                this.Boton_Edificar_casa.setEnabled(aux);
            }
            if(this.modeloQytetet.edificarHotel(calle)|| aux == false){
                this.Boton_edificar_hotel.setEnabled(aux);
            }
            if(this.modeloQytetet.hipotecarPropiedad(calle)|| aux == false){
                this.Boton_hipotecar_propiedad.setEnabled(aux);
            }
            if(!this.modeloQytetet.venderPropiedad(calle)|| aux == false){
                this.Boton_vender_propiedad.setEnabled(aux);
            }
        }else{
            this.Boton_vender_propiedad.setEnabled(aux);
            this.Boton_hipotecar_propiedad.setEnabled(aux);
            this.Boton_edificar_hotel.setEnabled(aux);
            this.Boton_Edificar_casa.setEnabled(aux);




        }
    }
    */
    public void actualizar(Qytetet modeloQytetet){
       // habilitarComenzarTurno();//Aqui no habria que hacerle el actualizar a VistaQytetet??????
        this.vistaQytetet.actualizar(modeloQytetet);
        this.repaint(); //Investiga para qué sirven estos métodos
        this.revalidate();
    }
    
}
